In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np
one_dimensional_array = np.array([10,12])
one_dimensional_array

array([10, 12])

In [5]:
## create numpy array
a = np.array([1,2,3])
print(a)
## create 3 integer starting from 0
b = np.arange(3)
print(b)

[1 2 3]
[0 1 2]


In [6]:
### create an aray that starts from integer 1 , ands with 20 and incremented with 3
start = 1
end   = 20
increment = 3
c = np.arange(start,end,increment)
print(c)

[ 1  4  7 10 13 16 19]
