In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np
one_dimensional_array = np.array([10,12])
one_dimensional_array

array([10, 12])

In [5]:
## create numpy array
a = np.array([1,2,3])
print(a)
## create 3 integer starting from 0
b = np.arange(3)
print(b)

[1 2 3]
[0 1 2]


In [6]:
### create an aray that starts from integer 1 , ands with 20 and incremented with 3
start = 1
end   = 20
increment = 3
c = np.arange(start,end,increment)
print(c)

[ 1  4  7 10 13 16 19]


In [7]:
!git add .;git commit -m "added";git push;

[main fbe150d] added
 3 files changed, 128 insertions(+)
 create mode 100644 MATH_FOR_MACHINE_LEARNING/1/.ipynb_checkpoints/INTRODUCTION_TO_NUMPY-checkpoint.ipynb
 create mode 100644 MATH_FOR_MACHINE_LEARNING/1/INTRODUCTION_TO_NUMPY.ipynb
 create mode 100644 MATH_FOR_MACHINE_LEARNING/1/screencapture-coursera-org-learn-machine-learning-linear-algebra-quiz-KupQT-solving-systems-of-linear-equations-attempt-2023-10-13-04_36_59.pdf
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 788.49 KiB | 2.89 MiB/s, done.
Total 8 (delta 1), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:tanviredu/BlockChain.git
   60c6831..fbe150d  main -> main
